In [17]:
import pandas as pd

In [20]:
hjDF=pd.read_csv('./서울특별시 행정동별 친환경자동차 현황-제원번호 포함 자료(2022.2.28).CSV', encoding='cp949')

In [21]:
hjDF

,기준년월,사용본거지시읍면동_행정동기준,차명,연료,최초등록일,현소유자의출생년도,제원관리번호
0,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200910,1977.0,01020007000041319
1,202202,서울특별시 강남구 개포1동,그랜저 하이브리드,하이브리드(휘발유+전기),20170710,1959.0,A0810010800451317
2,202202,서울특별시 강남구 개포1동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20210309,1942.0,01020006500091320
3,202202,서울특별시 강남구 개포1동,렉서스 ES300h,하이브리드(휘발유+전기),20210528,1966.0,01020006800021320
4,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200630,1970.0,01020007000041319
...,...,...,...,...,...,...,...
189581,202202,서울특별시 중랑구 중화2동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20180824,1982.0,01020006500001317
189582,202202,서울특별시 중랑구 중화2동,그랜저(GRANDEUR) 하이브리드,하이브리드(휘발유+전기),20150212,1979.0,A0810008700781314
189583,202202,서울특별시 중랑구 중화2동,니로 하이브리드,하이브리드(휘발유+전기),20180109,1979.0,A0110006100091217
189584,202202,서울특별시 중랑구 중화2동,포터Ⅱ 일렉트릭 (PORTERⅡ EL,전기,20210315,1967.0,A0810006219283120
189585,202202,NaN,K5 하이브리드,하이브리드(휘발유+전기),20120105,NaN,A0110004700101211

In [22]:
# 기준년월 unique :  202202밖에..
hjDF['기준년월']

<bound method Series.unique of 0         202202
1         202202
2         202202
3         202202
4         202202
           ...
189581    202202
189582    202202
189583    202202
189584    202202
189585    202202
Name: 기준년월, Length: 189586, dtype: int64>

In [24]:
hjDF['최초등록일'].

dtype('int64')

In [25]:
hjDF['최초등록일_날짜'] = pd.to_datetime(hjDF['최초등록일'])

In [27]:
hjDF

,기준년월,사용본거지시읍면동_행정동기준,차명,연료,최초등록일,현소유자의출생년도,제원관리번호,최초등록일_날짜
0,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200910,1977.0,01020007000041319,1970-01-01 00:00:00.020200910
1,202202,서울특별시 강남구 개포1동,그랜저 하이브리드,하이브리드(휘발유+전기),20170710,1959.0,A0810010800451317,1970-01-01 00:00:00.020170710
2,202202,서울특별시 강남구 개포1동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20210309,1942.0,01020006500091320,1970-01-01 00:00:00.020210309
3,202202,서울특별시 강남구 개포1동,렉서스 ES300h,하이브리드(휘발유+전기),20210528,1966.0,01020006800021320,1970-01-01 00:00:00.020210528
4,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200630,1970.0,01020007000041319,1970-01-01 00:00:00.020200630
...,...,...,...,...,...,...,...,...
189581,202202,서울특별시 중랑구 중화2동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20180824,1982.0,01020006500001317,1970-01-01 00:00:00.020180824
189582,202202,서울특별시 중랑구 중화2동,그랜저(GRANDEUR) 하이브리드,하이브리드(휘발유+전기),20150212,1979.0,A0810008700781314,1970-01-01 00:00:00.020150212
189583,202202,서울특별시 중랑구 중화2동,니로 하이브리드,하이브리드(휘발유+전기),20180109,1979.0,A0110006100091217,1970-01-01 00:00:00.020180109
189584,202202,서울특별시 중랑구 중화2동,포터Ⅱ 일렉트릭 (PORTERⅡ EL,전기,20210315,1967.0,A0810006219283120,1970-01-01 00:00:00.020210315
189585,202202,NaN,K5 하이브리드,하이브리드(휘발유+전기),20120105,NaN,A0110004700101211,1970-01-01 00:00:00.020120105

In [28]:
hjDF=hjDF.drop(['최초등록일_날짜'], axis=1)

In [29]:
hjDF

,기준년월,사용본거지시읍면동_행정동기준,차명,연료,최초등록일,현소유자의출생년도,제원관리번호
0,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200910,1977.0,01020007000041319
1,202202,서울특별시 강남구 개포1동,그랜저 하이브리드,하이브리드(휘발유+전기),20170710,1959.0,A0810010800451317
2,202202,서울특별시 강남구 개포1동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20210309,1942.0,01020006500091320
3,202202,서울특별시 강남구 개포1동,렉서스 ES300h,하이브리드(휘발유+전기),20210528,1966.0,01020006800021320
4,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200630,1970.0,01020007000041319
...,...,...,...,...,...,...,...
189581,202202,서울특별시 중랑구 중화2동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20180824,1982.0,01020006500001317
189582,202202,서울특별시 중랑구 중화2동,그랜저(GRANDEUR) 하이브리드,하이브리드(휘발유+전기),20150212,1979.0,A0810008700781314
189583,202202,서울특별시 중랑구 중화2동,니로 하이브리드,하이브리드(휘발유+전기),20180109,1979.0,A0110006100091217
189584,202202,서울특별시 중랑구 중화2동,포터Ⅱ 일렉트릭 (PORTERⅡ EL,전기,20210315,1967.0,A0810006219283120
189585,202202,NaN,K5 하이브리드,하이브리드(휘발유+전기),20120105,NaN,A0110004700101211

In [30]:
hjDF['최초등록일'].astype('str')

0         20200910
1         20170710
2         20210309
3         20210528
4         20200630
            ...
189581    20180824
189582    20150212
189583    20180109
189584    20210315
189585    20120105
Name: 최초등록일, Length: 189586, dtype: object

In [31]:
hjDF['최초등록일_날짜'] = pd.to_datetime(hjDF['최초등록일'])

In [32]:
hjDF

,기준년월,사용본거지시읍면동_행정동기준,차명,연료,최초등록일,현소유자의출생년도,제원관리번호,최초등록일_날짜
0,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200910,1977.0,01020007000041319,1970-01-01 00:00:00.020200910
1,202202,서울특별시 강남구 개포1동,그랜저 하이브리드,하이브리드(휘발유+전기),20170710,1959.0,A0810010800451317,1970-01-01 00:00:00.020170710
2,202202,서울특별시 강남구 개포1동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20210309,1942.0,01020006500091320,1970-01-01 00:00:00.020210309
3,202202,서울특별시 강남구 개포1동,렉서스 ES300h,하이브리드(휘발유+전기),20210528,1966.0,01020006800021320,1970-01-01 00:00:00.020210528
4,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200630,1970.0,01020007000041319,1970-01-01 00:00:00.020200630
...,...,...,...,...,...,...,...,...
189581,202202,서울특별시 중랑구 중화2동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20180824,1982.0,01020006500001317,1970-01-01 00:00:00.020180824
189582,202202,서울특별시 중랑구 중화2동,그랜저(GRANDEUR) 하이브리드,하이브리드(휘발유+전기),20150212,1979.0,A0810008700781314,1970-01-01 00:00:00.020150212
189583,202202,서울특별시 중랑구 중화2동,니로 하이브리드,하이브리드(휘발유+전기),20180109,1979.0,A0110006100091217,1970-01-01 00:00:00.020180109
189584,202202,서울특별시 중랑구 중화2동,포터Ⅱ 일렉트릭 (PORTERⅡ EL,전기,20210315,1967.0,A0810006219283120,1970-01-01 00:00:00.020210315
189585,202202,NaN,K5 하이브리드,하이브리드(휘발유+전기),20120105,NaN,A0110004700101211,1970-01-01 00:00:00.020120105

In [33]:
hjDF=hjDF.drop(['최초등록일_날짜'], axis=1)

In [34]:
hjDF

,기준년월,사용본거지시읍면동_행정동기준,차명,연료,최초등록일,현소유자의출생년도,제원관리번호
0,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200910,1977.0,01020007000041319
1,202202,서울특별시 강남구 개포1동,그랜저 하이브리드,하이브리드(휘발유+전기),20170710,1959.0,A0810010800451317
2,202202,서울특별시 강남구 개포1동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20210309,1942.0,01020006500091320
3,202202,서울특별시 강남구 개포1동,렉서스 ES300h,하이브리드(휘발유+전기),20210528,1966.0,01020006800021320
4,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200630,1970.0,01020007000041319
...,...,...,...,...,...,...,...
189581,202202,서울특별시 중랑구 중화2동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20180824,1982.0,01020006500001317
189582,202202,서울특별시 중랑구 중화2동,그랜저(GRANDEUR) 하이브리드,하이브리드(휘발유+전기),20150212,1979.0,A0810008700781314
189583,202202,서울특별시 중랑구 중화2동,니로 하이브리드,하이브리드(휘발유+전기),20180109,1979.0,A0110006100091217
189584,202202,서울특별시 중랑구 중화2동,포터Ⅱ 일렉트릭 (PORTERⅡ EL,전기,20210315,1967.0,A0810006219283120
189585,202202,NaN,K5 하이브리드,하이브리드(휘발유+전기),20120105,NaN,A0110004700101211

In [45]:
hjDF['최초등록일']=hjDF['최초등록일'].astype('str')

In [46]:
hjDF['최초등록일'].dtype

dtype('O')

In [49]:
hjDF['최초등록일_년도']=hjDF['최초등록일'].str[:4]

In [50]:
hjDF

,기준년월,사용본거지시읍면동_행정동기준,차명,연료,최초등록일,현소유자의출생년도,제원관리번호,최초등록일_년도
0,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200910,1977.0,01020007000041319,2020
1,202202,서울특별시 강남구 개포1동,그랜저 하이브리드,하이브리드(휘발유+전기),20170710,1959.0,A0810010800451317,2017
2,202202,서울특별시 강남구 개포1동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20210309,1942.0,01020006500091320,2021
3,202202,서울특별시 강남구 개포1동,렉서스 ES300h,하이브리드(휘발유+전기),20210528,1966.0,01020006800021320,2021
4,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200630,1970.0,01020007000041319,2020
...,...,...,...,...,...,...,...,...
189581,202202,서울특별시 중랑구 중화2동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20180824,1982.0,01020006500001317,2018
189582,202202,서울특별시 중랑구 중화2동,그랜저(GRANDEUR) 하이브리드,하이브리드(휘발유+전기),20150212,1979.0,A0810008700781314,2015
189583,202202,서울특별시 중랑구 중화2동,니로 하이브리드,하이브리드(휘발유+전기),20180109,1979.0,A0110006100091217,2018
189584,202202,서울특별시 중랑구 중화2동,포터Ⅱ 일렉트릭 (PORTERⅡ EL,전기,20210315,1967.0,A0810006219283120,2021
189585,202202,NaN,K5 하이브리드,하이브리드(휘발유+전기),20120105,NaN,A0110004700101211,2012

In [52]:
vcDF=pd.DataFrame(hjDF['최초등록일_년도'].value_counts())

In [55]:
vcDF.to_csv('년도별_valuecounts.csv')

In [56]:
vcDF

      최초등록일_년도
2021     50847
2020     35929
2019     23576
2018     20916
2017     16469
2016     10690
2015      6597
2022      5882
2014      5306
2012      4913
2013      4015
2011      2348
2010       960
2009       779
2008       207
2007       122
2006        24
2005         6

In [58]:
hjDF

,기준년월,사용본거지시읍면동_행정동기준,차명,연료,최초등록일,현소유자의출생년도,제원관리번호,최초등록일_년도
0,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200910,1977.0,01020007000041319,2020
1,202202,서울특별시 강남구 개포1동,그랜저 하이브리드,하이브리드(휘발유+전기),20170710,1959.0,A0810010800451317,2017
2,202202,서울특별시 강남구 개포1동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20210309,1942.0,01020006500091320,2021
3,202202,서울특별시 강남구 개포1동,렉서스 ES300h,하이브리드(휘발유+전기),20210528,1966.0,01020006800021320,2021
4,202202,서울특별시 강남구 개포1동,토요타 RAV4 Hybrid AWD,하이브리드(휘발유+전기),20200630,1970.0,01020007000041319,2020
...,...,...,...,...,...,...,...,...
189581,202202,서울특별시 중랑구 중화2동,토요타 Camry Hybrid,하이브리드(휘발유+전기),20180824,1982.0,01020006500001317,2018
189582,202202,서울특별시 중랑구 중화2동,그랜저(GRANDEUR) 하이브리드,하이브리드(휘발유+전기),20150212,1979.0,A0810008700781314,2015
189583,202202,서울특별시 중랑구 중화2동,니로 하이브리드,하이브리드(휘발유+전기),20180109,1979.0,A0110006100091217,2018
189584,202202,서울특별시 중랑구 중화2동,포터Ⅱ 일렉트릭 (PORTERⅡ EL,전기,20210315,1967.0,A0810006219283120,2021
189585,202202,NaN,K5 하이브리드,하이브리드(휘발유+전기),20120105,NaN,A0110004700101211,2012

In [57]:
hjDF.isna().sum()

기준년월                   0
사용본거지시읍면동_행정동기준       11
차명                     0
연료                     0
최초등록일                  0
현소유자의출생년도          44764
제원관리번호                 0
최초등록일_년도               0
dtype: int64

In [60]:
import numpy as np

In [64]:
hjDF['사용본거지시읍면동_행정동기준'].unique()

array(['서울특별시 강남구 개포1동', '서울특별시 강남구 개포2동', '서울특별시 강남구 개포4동',
       '서울특별시 강남구 논현1동', '서울특별시 강남구 논현2동', '서울특별시 강남구 대치1동',
       '서울특별시 동작구 상도1동', '서울특별시 동작구 상도2동', '서울특별시 동작구 상도3동',
       '서울특별시 동작구 상도4동', '서울특별시 동작구 신대방1동', '서울특별시 동작구 신대방2동',
       '서울특별시 동작구 흑석동', '서울특별시 마포구 공덕동', '서울특별시 강남구 대치2동',
       '서울특별시 마포구 대흥동', '서울특별시 마포구 도화동', '서울특별시 마포구 망원1동',
       '서울특별시 마포구 망원2동', '서울특별시 마포구 상암동', '서울특별시 마포구 서강동',
       '서울특별시 강남구 대치4동', '서울특별시 마포구 서교동', '서울특별시 마포구 성산1동',
       '서울특별시 마포구 성산2동', '서울특별시 마포구 신수동', '서울특별시 마포구 아현동',
       '서울특별시 강남구 도곡1동', '서울특별시 마포구 연남동', '서울특별시 마포구 염리동',
       '서울특별시 마포구 용강동', '서울특별시 강남구 도곡2동', '서울특별시 마포구 합정동',
       '서울특별시 서대문구 남가좌1동', '서울특별시 강남구 삼성1동', '서울특별시 서대문구 남가좌2동',
       '서울특별시 강남구 삼성2동', '서울특별시 서대문구 북가좌1동', '서울특별시 서대문구 북가좌2동',
       '서울특별시 강남구 세곡동', '서울특별시 서대문구 북아현동', '서울특별시 서대문구 신촌동',
       '서울특별시 서대문구 연희동', '서울특별시 서대문구 천연동', '서울특별시 강남구 수서동',
       '서울특별시 강남구 신사동', '서울특별시 서대문구 충현동', '서울특별시 서대문구 홍은1동',
       '서울특별시 강남구 압구정동', '서울특별시 서대문구 홍은2동', '서울특별시 서대문구 홍제1동',
       '서울특별시 강남구 역삼1동', '서울특별시 서대문구 홍제2동', '서울특별시 서대문구 홍제3동',
       '서울특별시 서초구 내곡동', '서울특별시 서초구 반포1동', '서울특별시 서초구 반포2동',
       '서울특별시 서초구 반포3동', '서울특별시 서초구 반포4동', '서울특별시 서초구 반포본동',
       '서울특별시 서초구 방배1동', '서울특별시 강남구 역삼2동', '서울특별시 서초구 방배2동',
       '서울특별시 서초구 방배3동', '서울특별시 강남구 일원1동', '서울특별시 서초구 방배4동',
       '서울특별시 강남구 일원2동', '서울특별시 강남구 일원본동', '서울특별시 서초구 방배본동',
       '서울특별시 서초구 서초1동', '서울특별시 강남구 청담동', '서울특별시 강동구 강일동',
       '서울특별시 강동구 고덕1동', '서울특별시 서초구 서초2동', '서울특별시 강동구 고덕2동',
       '서울특별시 서초구 서초3동', '서울특별시 서초구 서초4동', '서울특별시 서초구 양재1동',
       '서울특별시 서초구 양재2동', '서울특별시 서초구 잠원동', '서울특별시 성동구 금호1가동',
       '서울특별시 성동구 금호2.3가동', '서울특별시 성동구 금호4가동', '서울특별시 성동구 마장동',
       '서울특별시 성동구 사근동', '서울특별시 성동구 성수1가1동', '서울특별시 성동구 성수1가2동',
       '서울특별시 성동구 성수2가1동', '서울특별시 성동구 성수2가3동', '서울특별시 성동구 송정동',
       '서울특별시 성동구 옥수동', '서울특별시 성동구 왕십리2동', '서울특별시 성동구 왕십리도선동',
       '서울특별시 성동구 용답동', '서울특별시 성동구 응봉동', '서울특별시 성동구 행당1동',
       '서울특별시 성동구 행당2동', '서울특별시 성북구 길음1동', '서울특별시 강동구 길동',
       '서울특별시 성북구 길음2동', '서울특별시 성북구 돈암1동', '서울특별시 성북구 돈암2동',
       '서울특별시 강동구 둔촌2동', '서울특별시 강동구 명일1동', '서울특별시 성북구 동선동',
       '서울특별시 성북구 보문동', '서울특별시 성북구 삼선동', '서울특별시 강동구 명일2동',
       '서울특별시 성북구 석관동', '서울특별시 성북구 성북동', '서울특별시 강동구 상일동', '서울특별시 성북구 안암동',
       '서울특별시 성북구 월곡1동', '서울특별시 성북구 월곡2동', '서울특별시 강동구 상일제1동',
       '서울특별시 성북구 장위1동', '서울특별시 강동구 상일제2동', '서울특별시 강동구 성내1동',
       '서울특별시 성북구 장위2동', '서울특별시 성북구 장위3동', '서울특별시 성북구 정릉1동',
       '서울특별시 강동구 성내2동', '서울특별시 강동구 성내3동', '서울특별시 성북구 정릉2동',
       '서울특별시 강동구 암사1동', '서울특별시 성북구 정릉3동', '서울특별시 성북구 정릉4동',
       '서울특별시 강동구 암사2동', '서울특별시 성북구 종암동', '서울특별시 강동구 암사3동',
       '서울특별시 강동구 천호1동', '서울특별시 송파구 가락1동', '서울특별시 강동구 천호2동',
       '서울특별시 강동구 천호3동', '서울특별시 송파구 가락2동', '서울특별시 강북구 미아동',
       '서울특별시 강북구 번1동', '서울특별시 강북구 번2동', '서울특별시 강북구 번3동',
       '서울특별시 송파구 가락본동', '서울특별시 강북구 삼각산동', '서울특별시 송파구 거여1동',
       '서울특별시 강북구 삼양동', '서울특별시 송파구 거여2동', '서울특별시 강북구 송중동',
       '서울특별시 송파구 마천1동', '서울특별시 강북구 송천동', '서울특별시 송파구 마천2동',
       '서울특별시 강북구 수유1동', '서울특별시 강북구 수유2동', '서울특별시 송파구 문정1동',
       '서울특별시 강북구 수유3동', '서울특별시 강북구 우이동', '서울특별시 강북구 인수동',
       '서울특별시 송파구 문정2동', '서울특별시 강서구 가양1동', '서울특별시 송파구 방이1동',
       '서울특별시 송파구 방이2동', '서울특별시 송파구 삼전동', '서울특별시 송파구 석촌동',
       '서울특별시 송파구 송파1동', '서울특별시 송파구 송파2동', '서울특별시 송파구 오금동',
       '서울특별시 강서구 가양2동', '서울특별시 송파구 오륜동', '서울특별시 강서구 가양3동',
       '서울특별시 강서구 공항동', '서울특별시 송파구 위례동', '서울특별시 강서구 등촌1동',
       '서울특별시 강서구 등촌2동', '서울특별시 송파구 잠실2동', '서울특별시 강서구 등촌3동',
       '서울특별시 강서구 발산1동', '서울특별시 송파구 잠실3동', '서울특별시 강서구 방화1동',
       '서울특별시 송파구 잠실4동', '서울특별시 강서구 방화2동', '서울특별시 송파구 잠실6동',
       '서울특별시 강서구 방화3동', '서울특별시 송파구 잠실7동', '서울특별시 강서구 염창동',
       '서울특별시 송파구 잠실본동', '서울특별시 송파구 장지동', '서울특별시 강서구 우장산동',
       '서울특별시 송파구 풍납1동', '서울특별시 송파구 풍납2동', '서울특별시 강서구 화곡1동',
       '서울특별시 양천구 목1동', '서울특별시 강서구 화곡2동', '서울특별시 강서구 화곡3동',
       '서울특별시 양천구 목2동', '서울특별시 강서구 화곡4동', '서울특별시 강서구 화곡6동',
       '서울특별시 양천구 목3동', '서울특별시 강서구 화곡8동', '서울특별시 양천구 목4동',
       '서울특별시 강서구 화곡본동', '서울특별시 관악구 낙성대동', '서울특별시 양천구 목5동',
       '서울특별시 관악구 난곡동', '서울특별시 관악구 난향동', '서울특별시 관악구 남현동',
       '서울특별시 양천구 신월1동', '서울특별시 관악구 대학동', '서울특별시 양천구 신월2동',
       '서울특별시 관악구 미성동', '서울특별시 양천구 신월3동', '서울특별시 관악구 보라매동',
       '서울특별시 양천구 신월4동', '서울특별시 양천구 신월5동', '서울특별시 관악구 삼성동',
       '서울특별시 양천구 신월6동', '서울특별시 관악구 서림동', '서울특별시 양천구 신월7동',
       '서울특별시 관악구 서원동', '서울특별시 양천구 신정1동', '서울특별시 관악구 성현동',
       '서울특별시 관악구 신림동', '서울특별시 양천구 신정2동', '서울특별시 관악구 신사동',
       '서울특별시 양천구 신정3동', '서울특별시 관악구 신원동', '서울특별시 관악구 은천동',
       '서울특별시 관악구 인헌동', '서울특별시 양천구 신정4동', '서울특별시 관악구 조원동',
       '서울특별시 관악구 중앙동', '서울특별시 관악구 청룡동', '서울특별시 양천구 신정6동',
       '서울특별시 관악구 청림동', '서울특별시 양천구 신정7동', '서울특별시 관악구 행운동',
       '서울특별시 광진구 광장동', '서울특별시 영등포구 당산1동', '서울특별시 영등포구 당산2동',
       '서울특별시 광진구 구의1동', '서울특별시 광진구 구의2동', '서울특별시 영등포구 대림1동',
       '서울특별시 영등포구 대림2동', '서울특별시 광진구 구의3동', '서울특별시 영등포구 대림3동',
       '서울특별시 광진구 군자동', '서울특별시 영등포구 도림동', '서울특별시 광진구 능동',
       '서울특별시 영등포구 문래동', '서울특별시 광진구 자양1동', '서울특별시 광진구 자양2동',
       '서울특별시 광진구 자양3동', '서울특별시 영등포구 신길1동', '서울특별시 영등포구 신길3동',
       '서울특별시 광진구 자양4동', '서울특별시 영등포구 신길4동', '서울특별시 광진구 중곡1동',
       '서울특별시 영등포구 신길5동', '서울특별시 영등포구 신길6동', '서울특별시 광진구 중곡2동',
       '서울특별시 영등포구 신길7동', '서울특별시 광진구 중곡3동', '서울특별시 광진구 중곡4동',
       '서울특별시 광진구 화양동', '서울특별시 영등포구 양평1동', '서울특별시 구로구 가리봉동',
       '서울특별시 구로구 개봉1동', '서울특별시 영등포구 양평2동', '서울특별시 구로구 개봉2동',
       '서울특별시 영등포구 여의동', '서울특별시 구로구 개봉3동', '서울특별시 구로구 고척1동',
       '서울특별시 구로구 고척2동', '서울특별시 구로구 구로1동', '서울특별시 영등포구 영등포동',
       '서울특별시 구로구 구로2동', '서울특별시 구로구 구로3동', '서울특별시 영등포구 영등포본동',
       '서울특별시 용산구 남영동', '서울특별시 구로구 구로4동', '서울특별시 용산구 보광동',
       '서울특별시 용산구 서빙고동', '서울특별시 용산구 용문동', '서울특별시 용산구 용산2가동',
       '서울특별시 용산구 원효로1동', '서울특별시 용산구 원효로2동', '서울특별시 구로구 구로5동',
       '서울특별시 용산구 이촌1동', '서울특별시 구로구 수궁동', '서울특별시 구로구 신도림동',
       '서울특별시 용산구 이촌2동', '서울특별시 구로구 오류1동', '서울특별시 용산구 이태원1동',
       '서울특별시 용산구 이태원2동', '서울특별시 구로구 오류2동', '서울특별시 용산구 청파동',
       '서울특별시 용산구 한강로동', '서울특별시 구로구 항동', '서울특별시 금천구 가산동', '서울특별시 용산구 한남동',
       '서울특별시 용산구 효창동', '서울특별시 용산구 후암동', '서울특별시 은평구 갈현1동',
       '서울특별시 금천구 독산1동', '서울특별시 은평구 갈현2동', '서울특별시 은평구 구산동',
       '서울특별시 은평구 녹번동', '서울특별시 금천구 독산2동', '서울특별시 금천구 독산3동',
       '서울특별시 은평구 대조동', '서울특별시 금천구 독산4동', '서울특별시 금천구 시흥1동',
       '서울특별시 은평구 불광1동', '서울특별시 금천구 시흥2동', '서울특별시 은평구 불광2동',
       '서울특별시 금천구 시흥3동', '서울특별시 은평구 수색동', '서울특별시 금천구 시흥4동',
       '서울특별시 금천구 시흥5동', '서울특별시 은평구 신사1동', '서울특별시 노원구 공릉1동',
       '서울특별시 은평구 신사2동', '서울특별시 은평구 역촌동', '서울특별시 노원구 공릉2동',
       '서울특별시 은평구 응암1동', '서울특별시 노원구 상계10동', '서울특별시 은평구 응암2동',
       '서울특별시 노원구 상계1동', '서울특별시 은평구 응암3동', '서울특별시 노원구 상계2동',
       '서울특별시 은평구 증산동', '서울특별시 노원구 상계3.4동', '서울특별시 은평구 진관동',
       '서울특별시 노원구 상계5동', '서울특별시 노원구 상계6.7동', '서울특별시 노원구 상계8동',
       '서울특별시 종로구 가회동', '서울특별시 종로구 교남동', '서울특별시 노원구 상계9동',
       '서울특별시 종로구 무악동', '서울특별시 노원구 월계1동', '서울특별시 종로구 부암동',
       '서울특별시 노원구 월계2동', '서울특별시 종로구 사직동', '서울특별시 노원구 월계3동',
       '서울특별시 종로구 삼청동', '서울특별시 종로구 숭인1동', '서울특별시 종로구 숭인2동',
       '서울특별시 종로구 이화동', '서울특별시 노원구 중계1동', '서울특별시 종로구 종로1.2.3.4가동',
       '서울특별시 종로구 종로5.6가동', '서울특별시 종로구 창신1동', '서울특별시 노원구 중계2.3동',
       '서울특별시 종로구 창신2동', '서울특별시 종로구 창신3동', '서울특별시 종로구 청운효자동',
       '서울특별시 노원구 중계4동', '서울특별시 종로구 평창동', '서울특별시 노원구 중계본동',
       '서울특별시 종로구 혜화동', '서울특별시 노원구 하계1동', '서울특별시 중구 광희동', '서울특별시 중구 다산동',
       '서울특별시 노원구 하계2동', '서울특별시 중구 동화동', '서울특별시 중구 명동', '서울특별시 도봉구 도봉1동',
       '서울특별시 도봉구 도봉2동', '서울특별시 중구 소공동', '서울특별시 도봉구 방학1동',
       '서울특별시 중구 신당5동', '서울특별시 중구 신당동', '서울특별시 중구 약수동', '서울특별시 도봉구 방학2동',
       '서울특별시 도봉구 방학3동', '서울특별시 중구 을지로동', '서울특별시 중구 장충동', '서울특별시 중구 중림동',
       '서울특별시 도봉구 쌍문1동', '서울특별시 중구 청구동', '서울특별시 도봉구 쌍문2동',
       '서울특별시 도봉구 쌍문3동', '서울특별시 중구 필동', '서울특별시 중구 황학동', '서울특별시 도봉구 쌍문4동',
       '서울특별시 도봉구 창1동', '서울특별시 중구 회현동', '서울특별시 도봉구 창2동', '서울특별시 중랑구 망우3동',
       '서울특별시 도봉구 창3동', '서울특별시 도봉구 창4동', '서울특별시 중랑구 망우본동',
       '서울특별시 중랑구 면목2동', '서울특별시 도봉구 창5동', '서울특별시 중랑구 면목3.8동',
       '서울특별시 동대문구 답십리1동', '서울특별시 중랑구 면목4동', '서울특별시 중랑구 면목5동',
       '서울특별시 동대문구 답십리2동', '서울특별시 중랑구 면목7동', '서울특별시 중랑구 면목본동',
       '서울특별시 중랑구 묵1동', '서울특별시 동대문구 용신동', '서울특별시 중랑구 묵2동',
       '서울특별시 동대문구 이문1동', '서울특별시 동대문구 이문2동', '서울특별시 중랑구 상봉1동',
       '서울특별시 동대문구 장안1동', '서울특별시 중랑구 상봉2동', '서울특별시 중랑구 신내1동',
       '서울특별시 동대문구 장안2동', '서울특별시 중랑구 신내2동', '서울특별시 동대문구 전농1동',
       '서울특별시 중랑구 중화1동', '서울특별시 동대문구 전농2동', '서울특별시 중랑구 중화2동',
       '서울특별시 동대문구 제기동', nan, '서울특별시 동대문구 청량리동', '서울특별시 동대문구 회기동',
       '서울특별시 동대문구 휘경1동', '서울특별시 동대문구 휘경2동', '서울특별시 동작구 노량진1동',
       '서울특별시 동작구 노량진2동', '서울특별시 동작구 대방동', '서울특별시 동작구 사당1동',
       '서울특별시 동작구 사당2동', '서울특별시 동작구 사당3동', '서울특별시 동작구 사당4동',
       '서울특별시 동작구 사당5동', '서울특별시 강동구 둔촌1동'], dtype=object)

In [65]:
chargingDF=pd.read_csv('./한국전력공사_서울시 전기차 충전소 충전량_20220331.CSV', encoding='cp949')

In [66]:
chargingDF

,충전구분,충전소명,주소,충전기용량,충전량,충전시간,충전분,충전시작시각,충전종료시각
0,급속,영등포전력지사,서울특별시 영등포구 경인로 878,50.0,0.05,0.0,0.0,2021-01-01 2:06,2021-01-01 2:06
1,급속,영등포전력지사,서울특별시 영등포구 경인로 878,50.0,13.10,0.0,29.0,2021-01-02 14:58,2021-01-02 15:28
2,급속,영등포전력지사,서울특별시 영등포구 경인로 878,50.0,47.56,1.0,33.0,2021-01-02 20:57,2021-01-02 22:31
3,급속,영등포전력지사,서울특별시 영등포구 경인로 878,50.0,24.77,0.0,38.0,2021-01-04 12:12,2021-01-04 12:51
4,급속,영등포전력지사,서울특별시 영등포구 경인로 878,50.0,19.21,0.0,29.0,2021-01-04 22:51,2021-01-04 23:21
...,...,...,...,...,...,...,...,...,...
638697,급속,서울전력관리처,서울특별시 중구 퇴계로 140,50.0,41.67,1.0,21.0,2022-03-31 9:44,2022-03-31 11:05
638698,급속,서울전력관리처,서울특별시 중구 퇴계로 140,50.0,29.07,0.0,44.0,2022-03-31 12:17,2022-03-31 13:02
638699,급속,서울전력관리처,서울특별시 중구 퇴계로 140,50.0,55.65,1.0,21.0,2022-03-31 16:57,2022-03-31 18:19
638700,급속,서울전력관리처,서울특별시 중구 퇴계로 140,50.0,21.48,1.0,3.0,2022-03-31 13:06,2022-03-31 14:09
638701,급속,서울전력관리처,서울특별시 중구 퇴계로 140,50.0,13.56,0.0,24.0,2022-03-31 7:27,2022-03-31 7:51

In [67]:
chargingDF.isna().sum()

충전구분           0
충전소명           0
주소          1488
충전기용량     104677
충전량       103510
충전시간      103510
충전분       103510
충전시작시각    103510
충전종료시각    103510
dtype: int64

In [72]:
chargingDF[['충전구분', '충전소명', '주소']]

       충전구분     충전소명                  주소
0        급속  영등포전력지사  서울특별시 영등포구 경인로 878
1        급속  영등포전력지사  서울특별시 영등포구 경인로 878
2        급속  영등포전력지사  서울특별시 영등포구 경인로 878
3        급속  영등포전력지사  서울특별시 영등포구 경인로 878
4        급속  영등포전력지사  서울특별시 영등포구 경인로 878
...     ...      ...                 ...
638697   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638698   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638699   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638700   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638701   급속  서울전력관리처    서울특별시 중구 퇴계로 140

[638702 rows x 3 columns]

In [74]:
chargingDF[['충전구분', '충전소명', '주소']].isna().sum()

충전구분       0
충전소명       0
주소      1488
dtype: int64

In [111]:
chargingDF_2=chargingDF[['충전구분', '충전소명', '주소']]

In [112]:
chargingDF_2

       충전구분     충전소명                  주소
0        급속  영등포전력지사  서울특별시 영등포구 경인로 878
1        급속  영등포전력지사  서울특별시 영등포구 경인로 878
2        급속  영등포전력지사  서울특별시 영등포구 경인로 878
3        급속  영등포전력지사  서울특별시 영등포구 경인로 878
4        급속  영등포전력지사  서울특별시 영등포구 경인로 878
...     ...      ...                 ...
638697   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638698   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638699   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638700   급속  서울전력관리처    서울특별시 중구 퇴계로 140
638701   급속  서울전력관리처    서울특별시 중구 퇴계로 140

[638702 rows x 3 columns]

In [114]:
chargingDF_2 =chargingDF_2[chargingDF_2.duplicated() ==False].reset_index(drop = True)

In [122]:
chargingDF_2[chargingDF_2.isna().sum(1)>0]

    충전구분        충전소명   주소
152   급속  여의도KBS (본관  NaN
477   완속       면목두산2  NaN
485   완속       면목두산4  NaN
488   급속       면목두산4  NaN
516   급속       면목두산2  NaN

In [134]:
#chargingDF_2[chargingDF_2.isna().sum(1)>0]['주소'][152].fillna('서울 영등포구 여의공원로 13')

AttributeError: 'float' object has no attribute 'fillna'

In [135]:
# 조건식으로 찾아서 대체?
chargingDF_2['주소'][152]

0            서울특별시 영등포구 경인로 878
1            서울특별시 영등포구 경인로 878
2                경기도 하남시 감북로 80
3       서울특별시 강동구 구천면로 395(명일동)
4      서울특별시 송파구 마천동 성내천로37길 37
                 ...
870       서울특별시 강북구 월계로 173 (번동
871     서울특별시 성북구 동소문로 315 (길음동
872      서울특별시 강북구 삼각산로 85 (수유동
873            서울특별시 중구 퇴계로 140
874            서울특별시 중구 퇴계로 140
Name: 주소, Length: 875, dtype: object

In [133]:
chargingDF_2[chargingDF_2.isna().sum(1)>0]

    충전구분        충전소명   주소
152   급속  여의도KBS (본관  NaN
477   완속       면목두산2  NaN
485   완속       면목두산4  NaN
488   급속       면목두산4  NaN
516   급속       면목두산2  NaN

In [102]:
chargingDF_2

    충전구분           충전소명                        주소
0     급속        영등포전력지사        서울특별시 영등포구 경인로 878
1     완속        영등포전력지사        서울특별시 영등포구 경인로 878
2     완속       동서울 전력지사            경기도 하남시 감북로 80
3     급속      명일동 공영주차장   서울특별시 강동구 구천면로 395(명일동)
4     완속  송파파크데일1단지 아파트  서울특별시 송파구 마천동 성내천로37길 37
..   ...            ...                       ...
870   급속         북서울꿈의숲     서울특별시 강북구 월계로 173 (번동
871   급속      현대백화점 미아점   서울특별시 성북구 동소문로 315 (길음동
872   급속       강북문화예술회관    서울특별시 강북구 삼각산로 85 (수유동
873   급속        서울전력관리처          서울특별시 중구 퇴계로 140
874   완속        서울전력관리처          서울특별시 중구 퇴계로 140

[875 rows x 3 columns]

In [110]:
[add for add in chargingDF_2['주소'].str.split('(')]

[['서울특별시 영등포구 경인로 878'],
 ['서울특별시 영등포구 경인로 878'],
 ['경기도 하남시 감북로 80'],
 ['서울특별시 강동구 구천면로 395', '명일동)'],
 ['서울특별시 송파구 마천동 성내천로37길 37'],
 ['서울특별시 송파구 신천동 29-5 송파구청 앞'],
 ['서울특별시 송파구 송파동 오금로32길 14'],
 ['서울특별시 송파구 가락동 154'],
 ['서울특별시 강동구 둔촌동 522-9'],
 ['서울특별시 강동구 강일동 아리수로93길 40'],
 ['서울특별시 송파구 양재대로 932'],
 ['서울특별시 강동구 둔촌동 명일로 102'],
 ['서울특별시 송파구 잠실동 40'],
 ['서울특별시 송파구 장지동 516'],
 ['서울특별시 강동구 구천면로 42길 60', '천호동)'],
 ['서울특별시 송파구 잠실동 잠실로 88'],
 ['서울특별시 송파구 올림픽로 135'],
 ['서울특별시 강동구 성내동 풍성로 128'],
 ['서울특별시 강동구 천호동 천호대로 1089'],
 ['서울특별시 송파구 거여동 양산로4길 8'],
 ['서울특별시 송파구 거여동 195-1'],
 ['서울특별시 송파구 위례광장로 163 ', '장지동'],
 ['서울특별시 송파구 신천동 7-11'],
 ['서울특별시 강동구 명일동 260-1'],
 ['서울특별시 송파구 송파동 오금로32길 14'],
 ['서울특별시 송파구 잠실동 잠실로 88'],
 ['서울특별시 강동구 고덕동 동남로79길 26'],
 ['서울특별시 송파구 가락동 동남로 193'],
 ['서울특별시 송파구 충민로6길 14'],
 ['서울특별시 송파구 송파대로 8길 17'],
 ['서울특별시 송파구 풍납동 403-11'],
 ['서울특별시 송파구 신천동 올림픽로 269'],
 ['서울특별시 송파구 거여동 양산로4길 16'],
 ['서울특별시 송파구 올림픽로 135'],
 ['서울특별시 강동구 상일로 74'],
 ['서울특별시 강동구 양재대로 1571'],
 ['서울특별시 송파구 가락동 송파대로28길 27'],
 ['서울특별시 송파구 장지동 위례광장로 215'],
 ['서울특별시 송파구 충민로 4길 19'],
 ['서울특별시 송파구 올림픽로35길 93'],
 ['서울특별시 강동구 천호대로168길 58'],
 ['서울특별시 강동구 올림픽로 664'],
 ['서울특별시 송파구 송파대로 8길 17'],
 ['서울특별시 송파구 마천동 성내천로47길 38'],
 ['서울특별시 송파구 성내천로43길 6'],
 ['서울특별시 송파구 장지동 충민로4길 5'],
 ['서울특별시 송파구 충민로6길 14'],
 ['서울특별시 강동구 천호대로 1239', '길동)'],
 ['서울특별시 송파구 장지동 위례광장로 215'],
 ['서울특별시 송파구 삼전동 175-8'],
 ['서울특별시 송파구 장지동 380-1'],
 ['서울특별시 강동구 아리수로98길 25'],
 ['서울특별시 강동구 강일동 아리수로97길 20'],
 ['서울특별시 송파구 마천동 성내천로37길 37'],
 ['서울특별시 송파구 문정로 지하 12'],
 ['서울특별시 송파구 가락동 송파대로28길 27'],
 ['서울특별시 송파구 백제고분로 187'],
 ['서울특별시 송파구 위례광장로 163 ', '장지동'],
 ['서울특별시 송파구 문정동 문정로 83'],
 ['서울특별시 강동구 천호대로 1005'],
 ['서울특별시 송파구 거여동 양산로8길 8'],
 ['서울특별시 송파구 가락동 동남로 193'],
 ['서울특별시 송파구 거여동 양산로8길 8'],
 ['서울특별시 송파구 방이동 양재대로 1089'],
 ['서울특별시 송파구 장지동 380-1'],
 ['서울특별시 송파구 잠실동 40'],
 ['서울특별시 강동구 올림픽로91길 30 ', '암사동'],
 ['서울특별시 송파구 장지동 516'],
 ['서울특별시 송파구 장지동 위례광장로 270'],
 ['서울특별시 강동구 강일동 아리수로97길 20'],
 ['서울특별시 강동구 둔촌동 명일로 172'],
 ['서울특별시 송파구 마천동 성내천로47길 38'],
 ['서울특별시 강동구 양재대로95길 53 ', '성내동'],
 ['서울특별시 강동구 강일동 아리수로94길 19'],
 ['서울특별시 송파구 백제고분로44길 13-25'],
 ['서울특별시 강동구 천호대로 1239', '길동)'],
 ['서울특별시 송파구 장지동 송파대로8길 20'],
 ['서울특별시 송파구 장지동 833'],
 ['서울특별시 송파구 풍납동 토성로 38-6'],
 ['서울특별시 강동구 둔촌동 명일로 110'],
 ['서울특별시 송파구 풍납동 토성로 38-6'],
 ['서울특별시 강동구 길동 명일로 293'],
 ['서울특별시 강동구 성내동 풍성로 128'],
 ['서울특별시 강동구 상일로 152'],
 ['서울특별시 강동구 둔촌동 명일로 172'],
 ['서울특별시 강동구 상일로 74'],
 ['서울특별시 송파구 풍납동 올림픽로47길 9'],
 ['서울특별시 강동구 길동 명일로 293'],
 ['서울특별시 강동구 둔촌동 522-9'],
 ['서울특별시 강동구 고덕동 동남로79길 26'],
 ['서울특별시 강동구 강일동 아리수로93길 40'],
 ['서울특별시 강동구 명일동 동남로71길 19'],
 ['서울특별시 강동구 성내동 541-2'],
 ['서울특별시 송파구 거여동 양산로4길 8'],
 ['서울특별시 송파구 장지동 위례광장로 185'],
 ['서울특별시 송파구 거여동 양산로4길 16'],
 ['서울특별시 강동구 아리수로98길 25'],
 ['서울특별시 송파구 장지동 송파대로8길 20'],
 ['서울특별시 송파구 신천동 올림픽로 269'],
 ['서울특별시 강동구 강일동 고덕로97길 100'],
 ['서울특별시 송파구 장지동 충민로4길 5'],
 ['서울특별시 강동구 강일동 고덕로97길 20'],
 ['서울특별시 강동구 암사동 올림픽로104길 41'],
 ['서울특별시 강동구 암사동 고덕로 53'],
 ['서울특별시 강동구 암사동 올림픽로104길 41'],
 ['서울특별시 강동구 천호동 천호대로 1089'],
 ['서울특별시 강동구 둔촌동 명일로 102'],
 ['서울특별시 송파구 풍납동 풍성로26길 31'],
 ['서울특별시 강동구 성내동 풍성로53길 40'],
 ['서울특별시 송파구 풍납동 올림픽로47길 9'],
 ['서울특별시 송파구 문정동 문정로 83'],
 ['서울특별시 송파구 충민로 4길 19'],
 ['서울특별시 송파구 오금로62길 10'],
 ['서울특별시 송파구 가락동 중대로12길 35'],
 ['서울특별시 강동구 암사동 고덕로19길 30'],
 ['서울특별시 강동구 선사로 70 ', '천호동)'],
 ['서울특별시 송파구 동남로 263 ', '오금동'],
 ['서울특별시 강동구 동남로 870 ', '상일동'],
 ['서울특별시 영등포구 문래동3가 문래로 82'],
 ['서울특별시 영등포구 여의도동 의사당대로 127'],
 ['서울특별시 영등포구 도림동 도영로 66'],
 ['서울특별시 영등포구 대림동 870'],
 ['서울특별시 영등포구 문래동3가 당산로4길 12'],
 ['서울특별시 영등포구 문래동3가 80'],
 ['서울특별시 영등포구 영등포로 351'],
 ['서울특별시 영등포구 여의도동 21'],
 ['서울특별시 영등포구 당산동2가 16-1'],
 ['서울특별시 영등포구 여의도동 1'],
 ['서울특별시 영등포구 신길동 가마산로 540'],
 ['서울특별시 영등포구 신길동 신길로 119'],
 ['서울특별시 영등포구 신길동 대방천로14길 34'],
 ['서울특별시 영등포구 신길동 가마산로79길 7'],
 ['서울특별시 영등포구 대림동 608-1'],
 ['서울특별시 영등포구 문래동3가 당산로4길 12'],
 ['서울특별시 영등포구 신길동 가마산로79길 7'],
 ['서울특별시 영등포구 양평동5가 76'],
 ['서울특별시 영등포구 대림동 780'],
 ['서울특별시 영등포구 신길동 4945'],
 ['서울특별시 영등포구 문래동3가 97'],
 ['서울특별시 영등포구 양평동5가 76'],
 ['서울특별시 영등포구 문래동3가 93-1'],
 ['서울특별시 영등포구 여의도동 21'],
 ['서울특별시 영등포구 문래동3가 80'],
 ['서울특별시 영등포구 여의도동 의사당대로 127'],
 ['서울특별시 영등포구 영등포로 351'],
 ['서울특별시 영등포구 신길동 4945'],
 ['서울특별시 영등포구 당산동2가 16-1'],
 ['서울특별시 영등포구 도림동 도영로 66'],
 ['서울특별시 영등포구 대림동 608-1'],
 ['서울특별시 영등포구 당산로27길 12 ', '당산동3가)'],
 ['서울특별시 영등포구 선유동2로 6 ', '당산동4가'],
 ['서울특별시 영등포구 국회대로 596 ', '당산동3가'],
 nan,
 ['서울특별시 양천구 신정로11길 20 ', '신정동'],
 ['서울특별시 강서구 방화동 금낭화로 287-19'],
 ['서울특별시 강서구 공항대로 583'],
 ['서울특별시 양천구 신정이펜2로 55'],
 ['서울특별시 양천구 목동 961'],
 ['서울특별시 양천구 목동 908-28'],
 ['서울특별시 강서구 마곡동 725-1'],
 ['서울특별시 강서구 방화동 886'],
 ['서울특별시 양천구 목동 900'],
 ['서울특별시 강서구 마곡동 736'],
 ['서울특별시 강서구 방화동 금낭화로23길 8'],
 ['서울특별시 양천구 신정동 중앙로36길 15'],
 ['서울특별시 강서구 내발산동 742'],
 ['서울특별시 양천구 신월동 1026'],
 ['서울특별시 강서구 화곡동 1139'],
 ['서울특별시 강서구 내발산동 751'],
 ['서울특별시 강서구 수명로2길 108'],
 ['서울특별시 강서구 마곡동 743'],
 ['서울특별시 강서구 마곡동 마곡서1로 146'],
 ['서울특별시 양천구 신정동 319-1'],
 ['서울특별시 강서구 마곡동 748'],
 ['서울특별시 강서구 내발산동 749'],
 ['서울특별시 강서구 내발산동 749'],
 ['서울특별시 강서구 방화동 금낭화로 287-19'],
 ['서울특별시 양천구 목동 905-22'],
 ['서울특별시 강서구 마곡동 공항대로 124'],
 ['서울특별시 강서구 내발산동 수명로2길 63'],
 ['서울특별시 강서구 마곡동 736'],
 ['서울특별시 양천구 신정동 337'],
 ['서울특별시 강서구 마곡동 725-1'],
 ['서울특별시 양천구 신월동 263'],
 ['서울특별시 양천구 목동 961'],
 ['서울특별시 강서구 마곡동 748'],
 ['서울특별시 강서구 방화동 875'],
 ['서울특별시 강서구 마곡동 743'],
 ['서울특별시 강서구 마곡동 마곡서1로 81'],
 ['서울특별시 양천구 신정동 1324'],
 ['서울특별시 양천구 신정동 중앙로36길 15'],
 ['서울특별시 양천구 신정동 1281'],
 ['서울특별시 강서구 내발산동 수명로2가길 22'],
 ['서울특별시 강서구 가양동 양천로55길 55'],
 ['서울특별시 강서구 공항대로 351-21 ', '등촌동'],
 ['서울특별시 양천구 신정동 318-10'],
 ['서울특별시 강서구 염창동 306'],
 ['서울특별시 양천구 목동 755-1'],
 ['서울특별시 강서구 공항대로59길 64'],
 ['서울특별시 강서구 가양동 양천로55길 55'],
 ['서울특별시 양천구 신월동 남부순환로56길 9'],
 ['서울특별시 양천구 신월동 506-1'],
 ['서울특별시 양천구 신정동 319-1'],
 ['서울특별시 양천구 신월로20길 7'],
 ['서울특별시 양천구 신정동 1281'],
 ['서울특별시 양천구 신월동 1026'],
 ['서울특별시 강서구 내발산동 751'],
 ['서울특별시 강서구 내발산동 수명로2길 63'],
 ['서울특별시 양천구 신월동 217-8'],
 ['서울특별시 강서구 내발산동 수명로2가길 22'],
 ['서울특별시 강서구 마곡서1로 48 ', '마곡동'],
 ['서울특별시 양천구 목동 905-22'],
 ['서울특별시 양천구 신정동 318-10'],
 ['서울특별시 강서구 내발산동 742'],
 ['서울특별시 강서구 마곡중앙4로 74 ', '마곡동)'],
 ['서울특별시 양천구 목동동로 155 ', '신정동)'],
 ['서울특별시 양천구 목동중앙북로8다길 지하 4 ', '목동'],
 ['서울특별시 강서구 공항대로59길 64'],
 ['서울특별시 강서구 방화동 금낭화로23길 8'],
 ['서울특별시 양천구 목동동로 233 ', '목동'],
 ['서울특별시 양천구 신정로11길 20 ', '신정동'],
 ['서울특별시 양천구 월정로 46 ', '신월동)'],
 ['서울특별시 강서구 하늘길 78 ', '과해동'],
 ['서울특별시 강서구 화곡로 308 ', '화곡동'],
 ['서울특별시 양천구 목동동로 105 ', '신정동'],
 ['서울특별시 관악구 봉천동 인헌12길 46-1'],
 ['서울특별시 관악구 신사로 7'],
 ['서울특별시 동작구 동작동 동작대로39길 22'],
 ['서울특별시 관악구 봉천동 청룡길 78'],
 ['서울특별시 동작구 상도동 상도로 346-2'],
 ['서울특별시 관악구 신림동 난곡로 66'],
 ['서울특별시 동작구 상도동 상도로60길 20'],
 ['서울특별시 관악구 봉천동 보라매로 62'],
 ['서울특별시 관악구 봉천동 인헌12길 46-1'],
 ['서울특별시 동작구 상도동 장승배기로 11'],
 ['서울특별시 동작구 동작대로 19'],
 ['서울특별시 동작구 흑석동 흑석한강로 2'],
 ['서울특별시 관악구 신림동 호암로16길 5'],
 ['서울특별시 동작구 대방동 여의대방로44길 9'],
 ['서울특별시 관악구 봉천동 은천로 93'],
 ['서울특별시 동작구 신대방동 여의대방로10길 100'],
 ['서울특별시 동작구 신대방동 여의대방로 28'],
 ['서울특별시 동작구 신대방동 신대방1가길 38'],
 ['서울특별시 관악구 신림동 미성길 122'],
 ['서울특별시 동작구 사당동 사당로27길 190'],
 ['서울특별시 관악구 봉천동 1701'],
 ['서울특별시 관악구 신림동 신림로 11길 151'],
 ['서울특별시 동작구 상도동 장승배기로 11'],
 ['서울특별시 동작구 신대방동 신대방1가길 38'],
 ['서울특별시 동작구 동작대로 19'],
 ['서울특별시 관악구 신림동 광신길 86'],
 ['서울특별시 관악구 봉천동 은천로33길 5'],
 ['서울특별시 동작구 상도동 양녕로 287'],
 ['서울특별시 동작구 동작동 동작대로39길 22'],
 ['서울특별시 동작구 대방동 345-1'],
 ['서울특별시 관악구 봉천동 청룡길 78'],
 ['서울특별시 동작구 상도동 상도로 346-2'],
 ['서울특별시 관악구 신림동 미성길 122'],
 ['서울특별시 관악구 신림동 미성3길 16'],
 ['서울특별시 동작구 대방동 상도로 53길 8'],
 ['서울특별시 관악구 신림로3가길 45-24'],
 ['서울특별시 동작구 신대방동 보라매로5가길 16'],
 ['서울특별시 동작구 대방동 상도로 53길 8'],
 ['서울특별시 관악구 봉천동 은천로33길 5'],
 ['서울특별시 동작구 신대방동 여의대방로 28'],
 ['서울특별시 동작구 상도동 등용로 37'],
 ['서울특별시 관악구 봉천동 보라매로 62'],
 ['서울특별시 동작구 상도동 등용로 37'],
 ['서울특별시 동작구 대방동 여의대방로44길 9'],
 ['서울특별시 동작구 흑석동 흑석한강로 2'],
 ['서울특별시 관악구 남부순환로 1546 ', '신림동'],
 ['서울특별시 동작구 사당동 사당로27길 190'],
 ['서울특별시 동작구 국사봉16길 28 ', '상도동'],
 ['서울특별시 관악구 낙성대로3길 37 ', '봉천동'],
 ['서울특별시 동작구 노량진로 47 ', '대방동'],
 ['서울특별시 서초구 방배동 755-14'],
 ['서울특별시 서초구 우면동 735'],
 ['서울특별시 서초구 우면동 737'],
 ['서울특별시 서초구 효령로 72길 60'],
 ['서울특별시 서초구 신원동 374'],
 ['서울특별시 서초구 서초동 1301-6'],
 ['서울특별시 서초구 반포동 30-26'],
 ['서울특별시 서초구 서초동 산 130-19'],
 ['서울특별시 null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null'],
 ['서울특별시 서초구 신원동 374'],
 ['서울특별시 서초구 서초동 1681-8'],
 ['서울특별시 서초구 방배동 774-19'],
 ['서울특별시 서초구 서초동 1456-2'],
 ['서울특별시 서초구 방배동 772-13'],
 ['경기도 과천시 별양동 별양로 163'],
 ['서울특별시 서초구 우면동 368-1'],
 ['서울특별시 서초구 우면동 753'],
 ['서울특별시 서초구 방배동 3275'],
 ['서울특별시 서초구 우면동 773'],
 ['서울특별시 서초구 반포동 2-12'],
 ['서울특별시 서초구 내곡동 77'],
 ['서울특별시 서초구 내곡동 6-7'],
 ['서울특별시 서초구 우면동 788'],
 ['서울특별시 서초구 내곡동 77'],
 ['서울특별시 서초구 우면동 773'],
 ['서울특별시 서초구 우면동 753'],
 ['서울특별시 서초구 반포동 동광로32길 7'],
 ['서울특별시 서초구 서초동 1542-1'],
 ['서울특별시 서초구 반포동 19-3'],
 ['서울특별시 서초구 방배동 797-30'],
 ['서울특별시 서초구 서초동 1529'],
 ['서울특별시 서초구 우면동 707'],
 ['서울특별시 서초구 방배동 884-2'],
 ['서울특별시 서초구 우면동 763'],
 ['서울특별시 서초구 방배동 754-1'],
 ['서울특별시 서초구 반포동 60-4'],
 ['서울특별시 서초구 서초동 1642-14'],
 ['서울특별시 서초구 우면동 737'],
 ['서울특별시 서초구 방배동 3277'],
 ['서울특별시 서초구 우면동 368-1'],
 ['서울특별시 서초구 방배동 844-1'],
 ['서울특별시 서초구 효령로 72길 60'],
 ['서울특별시 서초구 방배동 754-1'],
 ['서울특별시 서초구 반포동 30-26'],
 ['서울특별시 서초구 반포동 산 94-1'],
 ['서울특별시 서초구 서초동 1301-6'],
 ['서울특별시 서초구 반포대로22길 86'],
 ['서울특별시 서초구 서초동 1642-34'],
 ['서울특별시 null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null'],
 ['서울특별시 서초구 잠원로3길 40'],
 ['서울특별시 서초구 주흥5길 20 ', '반포동)'],
 ['서울특별시 서초구 잠원동 10-33'],
 ['서울특별시 서초구 서초동 1444-19'],
 ['서울특별시 서초구 서초동 1338'],
 ['서울특별시 서초구 서초동 1549-3'],
 ['서울특별시 서초구 양재동 399'],
 ['서울특별시 서초구 강남대로8길 77 ', '양재동'],
 ['서울특별시 서초구 헌릉로 13 ', '염곡동'],
 ['서울특별시 서초구 동작대로 22-2 ', '방배동'],
 ['서울특별시 서초구 헌릉로 25 ', '염곡동'],
 ['서울특별시 서초구 매헌로 16 ', '양재동'],
 ['경기도 과천시 중앙로 294 ', '관문동'],
 ['경기도 과천시 문원로 56 ', '문원동'],
 ['경기도 과천시 통영로 5 ', '중앙동'],
 ['경기도 과천시 용마로 13 ', '과천동'],
 ['경기도 과천시 과천대로 608-17 ', '과천동'],
 ['경기도 과천시 대공원광장로 102 ', '막계동'],
 ['서울특별시 강남구 자곡동 자곡로 175'],
 ['서울특별시 강남구 도곡동 언주로30길 56'],
 ['서울특별시 강남구 역삼동 757'],
 ['서울특별시 강남구 역삼동 757'],
 ['서울특별시 강남구 역삼동 755-1'],
 ['서울특별시 강남구 역삼동 역삼로 306'],
 ['서울특별시 강남구 세곡동 533'],
 ['서울특별시 강남구 대치동 도곡로93길 12'],
 ['서울특별시 강남구 신사동 압구정로42길 78'],
 ['서울특별시 강남구 자곡동 자곡로3길 21'],
 ['서울특별시 강남구 도곡동 선릉로 221'],
 ['서울특별시 강남구 도곡동 언주로30길 26'],
 ['서울특별시 강남구 자곡동 자곡로 260'],
 ['서울특별시 강남구 세곡동 헌릉로590길 63'],
 ['서울특별시 강남구 삼성동 16-1'],
 ['서울특별시 강남구 율현동 밤고개로26길 50'],
 ['서울특별시 강남구 영동대로65길 24'],
 ['서울특별시 강남구 선릉로 121길 12'],
 ['서울특별시 강남구 청담동 학동로97길 31'],
 ['서울특별시 강남구 일원동 일원로 127'],
 ['서울특별시 강남구 자곡동 자곡로3길 21'],
 ['서울특별시 강남구 일원동 일원로 120'],
 ['서울특별시 강남구 언주로 211'],
 ['서울특별시 강남구 대치동 삼성로64길 5'],
 ['서울특별시 강남구 도곡동 선릉로 221'],
 ['서울특별시 강남구 자곡동 자곡로 101'],
 ['서울특별시 강남구 자곡동 자곡로 175'],
 ['서울특별시 강남구 세곡동 헌릉로590길 11'],
 ['서울특별시 강남구 역삼동 도곡로43길 20'],
 ['서울특별시 강남구 도곡동 언주로30길 26'],
 ['서울특별시 강남구 도곡동 언주로30길 56'],
 ['서울특별시 강남구 삼성로 111길 8'],
 ['서울특별시 강남구 자곡동 자곡로 101'],
 ['서울특별시 강남구 청담동 영동대로142길 16'],
 ['서울특별시 강남구 영동대로85길 17'],
 ['서울특별시 강남구 삼성동 영동대로 640'],
 ['서울특별시 강남구 자곡동 자곡로 260'],
 ['서울특별시 강남구 대치동 삼성로64길 5'],
 ['서울특별시 강남구 율현동 101-13'],
 ['서울특별시 강남구 역삼동 도곡로57길 12'],
 ['서울특별시 강남구 세곡동 헌릉로590길 11'],
 ['서울특별시 강남구 수서동 광평로34길55'],
 ['서울특별시 강남구 청담동 영동대로138길 12'],
 ['서울특별시 강남구 도곡동 언주로30길 57'],
 ['서울특별시 강남구 삼성동 48'],
 ['서울특별시 강남구 청담동 영동대로138길 12'],
 ['서울특별시 강남구 역삼동 755-4'],
 ['서울특별시 강남구 일원동 개포로110길 15'],
 ['서울특별시 강남구 세곡동 헌릉로 590길10'],
 ['서울특별시 강남구 일원동 개포로110길 15'],
 ['서울특별시 강남구 세곡동 533'],
 ['서울특별시 강남구 삼성동 학동로64길 14'],
 ['서울특별시 강남구 대치동 삼성로51길 37'],
 ['서울특별시 강남구 역삼동 도곡로43길 20'],
 ['서울특별시 강남구 율현동 밤고개로27길 20'],
 ['서울특별시 강남구 삼성동 3-8'],
 ['서울특별시 강남구 삼성동 학동로68길 30'],
 ['서울특별시 강남구 삼성동 봉은사로109길 14-8'],
 ['서울특별시 강남구 삼성로67길 14'],
 ['서울특별시 강남구 논현동 276-1'],
 ['서울특별시 강남구 도곡동 언주로30길 57'],
 ['서울특별시 강남구 삼성동 103-22'],
 ['서울특별시 강남구 세곡동 헌릉로590길 63'],
 ['서울특별시 강남구 역삼동 710'],
 ['서울특별시 강남구 도곡동 언주로30길 13'],
 ['서울특별시 강남구 역삼동 역삼로 306'],
 ['서울특별시 강남구 삼성동 삼성로99길 14'],
 ['서울특별시 강남구 논현동 276-1'],
 ['서울특별시 강남구 삼성로 111길 8'],
 ['서울특별시 강남구 세곡동 508'],
 ['서울특별시 강남구 삼성동 봉은사로111길 25'],
 ['서울특별시 강남구 대치동 도곡로93길 12'],
 ['서울특별시 강남구 수서동 광평로34길55'],
 ['서울특별시 강남구 율현동 밤고개로26길 50'],
 ['서울특별시 강남구 삼성동 봉은사로 645'],
 ['서울특별시 강남구 역삼동 755-4'],
 ['서울특별시 강남구 언주로 508 ', '역삼동'],
 ['서울특별시 구로구 개봉동 475'],
 ['서울특별시 금천구 시흥동 1020'],
 ['서울특별시 구로구 신도림로 87'],
 ['서울특별시 구로구 고척동 63-6'],
 ['서울특별시 구로구 오류동 오류로 30'],
 ['서울특별시 구로구 구로동 435'],
 ['서울특별시 구로구 오류동 346'],
 ['서울특별시 구로구 구로동 501'],
 ['서울특별시 구로구 구로동 256-1'],
 ['서울특별시 구로구 고척로 45길 39'],
 ['서울특별시 금천구 범안로 17길 1'],
 ['서울특별시 구로구 신도림로 87'],
 ['서울특별시 구로구 항동 119-12'],
 ['서울특별시 구로구 고척동 339'],
 ['서울특별시 금천구 독산동 152-1'],
 ['서울특별시 구로구 고척동 339'],
 ['서울특별시 구로구 가마산로25길 21 ', '구로동'],
 ['서울특별시 구로구 고척동 경인로 390'],
 ['서울특별시 금천구 가산디지털1로 33-33'],
 ['서울특별시 구로구 신도림동 신도림로 56-13'],
 ['서울특별시 구로구 개봉동 475'],
 ['서울특별시 구로구 구로동 741-44'],
 ['서울특별시 금천구 시흥동 시흥대로 165'],
 ['서울특별시 구로구 구로동 1263'],
 ['서울특별시 구로구 고척동 경인로 390'],
 ['서울특별시 구로구 구로동 46-7'],
 ['서울특별시 구로구 천왕동 천왕로 92'],
 ['서울특별시 구로구 구로동로47길 24 ', '구로동'],
 ['서울특별시 구로구 구로동 256-1'],
 ['서울특별시 구로구 구로동 1263'],
 ['서울특별시 구로구 가마산로25길 21 ', '구로동'],
 ['서울특별시 금천구 시흥동 시흥대로 165'],
 ['서울특별시 구로구 고척동 327'],
 ['서울특별시 구로구 오류동 오류로 30'],
 ['서울특별시 구로구 고척동 327'],
 ['서울특별시 구로구 고척동 340'],
 ['서울특별시 구로구 고척동 340'],
 ['서울특별시 구로구 천왕동 천왕로 29'],
 ['서울특별시 구로구 천왕동 천왕로 10'],
 ['서울특별시 구로구 개봉동 477'],
 ['서울특별시 구로구 오류동 346'],
 ['서울특별시 구로구 천왕동 천왕로 10'],
 ['서울특별시 구로구 천왕동 천왕로 92'],
 ['서울특별시 구로구 천왕동 천왕로 29'],
 ['서울특별시 구로구 구로중앙로 13 ', '구로동'],
 ['서울특별시 구로구 고척동 경인로47길 150'],
 ['서울특별시 구로구 구로동 1283'],
 ['서울특별시 구로구 벚꽃로 370 ', '가리봉동'],
 ['서울특별시 구로구 구로동 가마산로 283'],
 ['서울특별시 금천구 시흥대로79길 32 ', '독산동'],
 ['서울특별시 서초구 서초동 1355'],
 ['서울특별시 동대문구 장안동 장안벚꽃로1길 7'],
 ['서울특별시 동대문구 망우로 18나길 20'],
 ['서울특별시 중랑구 묵동 공릉로18길 59'],
 ['서울특별시 동대문구 휘경동 장안벚꽃로5길 19'],
 ['서울특별시 동대문구 이문동 한천로58길 47'],
 ['서울특별시 동대문구 휘경동 한천로 248'],
 ['서울특별시 동대문구 답십리로 130'],
 nan,
 ['서울특별시 동대문구 이문동 한천로58길 47'],
 ['서울특별시 중랑구 상봉동 봉화산로 130'],
 ['서울특별시 동대문구 전농동 사가정로 148'],
 ['서울특별시 중랑구 면목동 1081-1'],
 ['서울특별시 동대문구 휘경동 망우로20길 86'],
 ['서울특별시 중랑구 상봉동 상봉중앙로1다길 21'],
 ['서울특별시 중랑구 동일로 862'],
 nan,
 ['서울특별시 동대문구 장안동 장안벚꽃로1길 7'],
 ['서울특별시 동대문구 답십리동 한천로37길 33'],
 nan,
 ['서울특별시 동대문구 휘경동 한천로 248'],
 ['서울특별시 동대문구 회기동 1-1'],
 ['서울특별시 중랑구 묵동 동일로 932'],
 ['서울특별시 동대문구 답십리동 한천로37길 33'],
 ['서울특별시 중랑구 상봉동 망우로 346'],
 ['서울특별시 중랑구 면목동 동일로 483'],
 ['서울특별시 동대문구 전농로10길 20'],
 ['서울특별시 동대문구 한천로 300'],
 ['서울특별시 중랑구 신내동 신내역로1길 85'],
 ['서울특별시 동대문구 답십리로 130'],
 ['서울특별시 중랑구 묵동 숙선옹주로 6-9'],
 ['서울특별시 중랑구 상봉동 망우로 346'],
 ['서울특별시 동대문구 답십리로 130'],
 ['서울특별시 중랑구 신내동 신내로17길 41'],
 ['서울특별시 중랑구 망우동 양원역로 6'],
 ['서울특별시 중랑구 봉화산로48길 62'],
 ['서울특별시 중랑구 묵동 동일로 932'],
 ['서울특별시 중랑구 상봉동 상봉중앙로1다길 21'],
 ['서울특별시 중랑구 동일로 862'],
 ['서울특별시 동대문구 천호대로55길 11 ', '답십리동'],
 ['서울특별시 중랑구 망우동 망우로75길 19'],
 ['서울특별시 동대문구 휘경동 장안벚꽃로5길 19'],
 ['서울특별시 동대문구 답십리로 130'],
 ['서울특별시 동대문구 전농로10길 20'],
 ['서울특별시 중랑구 신내동 신내로17길 41'],
 ['서울특별시 중랑구 묵동 숙선옹주로 6-9'],
 ['서울특별시 중랑구 신내동 신내역로1길 85'],
 nan,
 ['서울특별시 중랑구 상봉동 봉화산로 130'],
 ['서울특별시 중랑구 중랑역로 9 ', '중화동'],
 ['서울특별시 중랑구 망우동 망우로75길 19'],
 ['서울특별시 중랑구 망우로62길 52-4 ', '망우동'],
 ['서울특별시 중랑구 봉화산로 123 ', '상봉동'],
 ['서울특별시 동대문구 왕산로 214 ', '전농동'],
 ['서울특별시 성동구 성수동2가 성수이로 137'],
 ['서울특별시 광진구 자양동 아차산로 262'],
 ['서울특별시 광진구 자양로 117'],
 ['서울특별시 광진구 뚝섬로 52길 74'],
 ['서울특별시 광진구 자양3동 510-8'],
 ['서울특별시 성동구 응봉동 고산자로4길 34'],
 ['서울특별시 광진구 광장동 아차산로 537-17'],
 ['서울특별시 성동구 왕십리로 410'],
 ['서울특별시 광진구 광나루로56길 85 ', '구의동'],
 ['서울특별시 성동구 금호동1가 금호로 140'],
 ['서울특별시 성동구 행당동 행당로 82'],
 ['서울특별시 성동구 하왕십리동 843'],
 ['서울특별시 성동구 금호동2가 금호로 117'],
 ['서울특별시 성동구 성수동2가 성수이로 137'],
 ['서울특별시 광진구 자양3동 510-8'],
 ['서울특별시 광진구 광나루로56길 85 ', '구의동'],
 ['서울특별시 광진구 광장동 아차산로 537-17'],
 ['서울특별시 성동구 하왕십리동 674-1'],
 ['서울특별시 성동구 자동차시장길 49'],
 ['서울특별시 성동구 금호동4가 금호로 15'],
 ['서울특별시 성동구 응봉동 고산자로4길 34'],
 ['서울특별시 성동구 왕십리로 222 ', '사근동)'],
 ['서울특별시 성동구 왕십리로 410'],
 ['서울특별시 성동구 금호동2가 금호로 117'],
 ['서울특별시 광진구 광장로5길 25-1'],
 ['서울특별시 광진구 구의강변로 106 ', '구의동'],
 ['서울특별시 성동구 행당동 행당로 82'],
 ['서울특별시 성동구 마장로27길 13'],
 ['서울특별시 성동구 마장로27길 13'],
 ['서울특별시 성동구 왕십리로 410'],
 ['서울특별시 광진구 구의강변로 106 ', '구의동'],
 ['서울특별시 광진구 자양동 구의강변로1길 44'],
 ['서울특별시 성동구 뚝섬로1길 31 ', '성수동1가'],
 ['서울특별시 광진구 자양동 아차산로36길 13'],
 ['서울특별시 광진구 자양동 아차산로 262'],
 ['서울특별시 성동구 왕십리로 410'],
 ['서울특별시 성동구 하왕십리동 843'],
 ['서울특별시 성동구 성수동1가 상원6길 16'],
 ['서울특별시 성동구 하왕십리동 674-1'],
 ['서울특별시 광진구 자양동 뚝섬로34길 25-19'],
 ['서울특별시 성동구 금호동1가 금호로 140'],
 ['서울특별시 성동구 성수일로8길 5 ', '성수동2가'],
 ['서울특별시 성동구 금호로 20 ', '금호동4가)'],
 ['서울특별시 성동구 성수동1가 685-63번지'],
 ['서울특별시 도봉구 창동 도봉로 428'],
 ['서울특별시 노원구 중계동 덕릉로76길 29'],
 ['서울특별시 도봉구 창동 노해로69길 103'],
 ['서울특별시 도봉구 창동 노해로69길 103'],
 ['서울특별시 도봉구 도봉로 678'],
 ['서울특별시 노원구 섬밭로 265 ', '중계동'],
 ['서울특별시 노원구 상계동 701-1'],
 ['서울특별시 노원구 공릉로 232'],
 ['서울특별시 도봉구 창동 노해로 403'],
 ['서울특별시 도봉구 도봉로 552 ', '창동'],
 ['서울특별시 노원구 화랑로 815'],
 ['서울특별시 도봉구 창동 마들로 551'],
 ['서울특별시 도봉구 노해로70길 126 ', '창동'],
 ['서울특별시 도봉구 창동 도봉로136길 111'],
 ['서울특별시 도봉구 덕릉로63가길 43 ', '창동'],
 ['서울특별시 노원구 동일로227길 86 ', '상계동'],
 ['서울특별시 노원구 상계동 상계로5길 12'],
 ['서울특별시 노원구 한글비석로 15길 51'],
 ['서울특별시 도봉구 방학동 해등로 286-5'],
 ['서울특별시 노원구 하계동 동일로207길 186'],
 ['서울특별시 도봉구 마들로 616'],
 ['서울특별시 노원구 중계동 덕릉로76길 29'],
 ['서울특별시 노원구 중계동 노원로22길 34'],
 ['서울특별시 도봉구 우이천로 367'],
 ['서울특별시 노원구 덕릉로70가길 21 ', '상계동'],
 ['서울특별시 도봉구 도봉동 도봉산길 35'],
 ['서울특별시 도봉구 시루봉로 11길 25-8'],
 ['서울특별시 도봉구 창동 노해로 403'],
 ['서울특별시 도봉구 마들로 656 ', '방학동'],
 ['서울특별시 노원구 공릉동 화랑로51길 17'],
 ['서울특별시 노원구 공릉동 670-20'],
 ['서울특별시 도봉구 쌍문동 388-1'],
 ['서울특별시 노원구 상계동 652'],
 ['서울특별시 노원구 월계동 석계로13길 35'],
 ['서울특별시 노원구 상계동 덕릉로 780'],
 ['서울특별시 도봉구 도봉동 도봉로180길 6-23'],
 ['서울특별시 노원구 중계동 중계로 195'],
 ['서울특별시 도봉구 방학동 방학로12길 53'],
 ['서울특별시 노원구 공릉동 동일로195길 39'],
 ['서울특별시 노원구 상계동 동일로250길 18'],
 ['서울특별시 노원구 동일로183길 34'],
 ['서울특별시 도봉구 마들로 684-20'],
 ['서울특별시 노원구 동일로227길 86 ', '상계동'],
 ['서울특별시 도봉구 창동 도봉로136길 111'],
 ['서울특별시 노원구 공릉동 공릉로 213'],
 ['서울특별시 노원구 상계동 상계로5길 12'],
 ['서울특별시 도봉구 마들로 735-8'],
 ['서울특별시 노원구 노원로22길 71 ', '중계동'],
 ['서울특별시 노원구 노원로22길 71 ', '중계동'],
 ['서울특별시 노원구 공릉동 91'],
 ['서울특별시 노원구 공릉동 화랑로51길 17'],
 ['서울특별시 노원구 동일로 1238 ', '중계동'],
 ['서울특별시 노원구 월계동 초안산로 89'],
 ['서울특별시 노원구 월계동 화랑로 355'],
 ['서울특별시 노원구 공릉동 화랑로51길 78'],
 ['서울특별시 도봉구 방학동 방학로 200'],
 ['서울특별시 도봉구 마들로 735-8'],
 ['서울특별시 도봉구 창동 덕릉로60바길 21'],
 ['서울특별시 도봉구 시루봉로 58'],
 ['서울특별시 도봉구 도봉동 도봉로180길 6-23'],
 ['서울특별시 노원구 월계동 초안산로 89'],
 ['서울특별시 노원구 중계동 덕릉로 613'],
 ['서울특별시 노원구 노해로 429 ', '상계동'],
 ['서울특별시 도봉구 방학동 도봉로150길 43'],
 ['서울특별시 도봉구 마들로 616'],
 ['서울특별시 노원구 상계동 누원로 28'],
 ['서울특별시 도봉구 방학동 도봉로150바길 26'],
 ['서울특별시 도봉구 시루봉로2길 62 ', '쌍문동'],
 ['서울특별시 노원구 공릉동 공릉로 206'],
 ['서울특별시 노원구 중계동 노원로22길 34'],
 ['서울특별시 노원구 공릉동 화랑로51길 78'],
 ['서울특별시 노원구 상계동 누원로 28'],
 ['서울특별시 노원구 상계동 덕릉로 780'],
 ['서울특별시 도봉구 도봉동 도봉산길 35'],
 ['서울특별시 노원구 하계동 동일로207길 186'],
 ['서울특별시 도봉구 방학동 방학로 200'],
 ['서울특별시 도봉구 창동 도봉로 642-30'],
 ['서울특별시 도봉구 방학동 방학로11길 33'],
 ['서울특별시 노원구 공릉동 공릉로 213'],
 ['서울특별시 노원구 공릉동 섬밭로 52'],
 ['서울특별시 노원구 공릉동 동일로175길 38'],
 ['서울특별시 노원구 상계동 상계로7길 18'],
 ['서울특별시 노원구 상계동 한글비석로52길 66'],
 ['서울특별시 노원구 상계동 한글비석로52길 66'],
 ['서울특별시 도봉구 시루봉로 58'],
 ['서울특별시 노원구 공릉동 섬밭로 156'],
 ['서울특별시 도봉구 우이천로 367'],
 ['서울특별시 도봉구 시루봉로 6길53'],
 ['서울특별시 도봉구 덕릉로 60길 164-13'],
 ['서울특별시 도봉구 창동 우이천로20길 6'],
 ['서울특별시 도봉구 쌍문동 우이천로30길 28'],
 ['서울특별시 도봉구 덕릉로 60길 164-13'],
 ['서울특별시 노원구 중계동 중계로14나길 25'],
 ['서울특별시 노원구 중계동 중계로14나길 25'],
 ['서울특별시 노원구 공릉동 섬밭로 139'],
 ['서울특별시 노원구 공릉동 섬밭로 139'],
 ['서울특별시 노원구 중계동 중계로8길 39'],
 ['서울특별시 노원구 중계동 중계로 195'],
 ['서울특별시 노원구 노원로 75 ', '공릉동'],
 ['서울특별시 도봉구 방학동 해등로 286-5'],
 ['서울특별시 노원구 공릉동 공릉로27길 110'],
 ['서울특별시 노원구 노해로 429 ', '상계동'],
 ['서울특별시 도봉구 방학로10길 51 ', '방학동'],
 ['서울특별시 도봉구 시루봉로 94 ', '방학동'],
 ['서울특별시 도봉구 덕릉로62길 89 ', '창동'],
 ['서울특별시 서대문구 홍은중앙로 125'],
 ['서울특별시 서대문구 북가좌동 481'],
 ['서울특별시 은평구 백련산로 90'],
 ['서울특별시 은평구 진관동 65-31'],
 ['서울특별시 서대문구 연희동 739'],
 ['서울특별시 서대문구 북가좌동 481'],
 ['서울특별시 서대문구 남가좌동 377'],
 ['서울특별시 서대문구 증가로 150 ', '남가좌동'],
 ['서울특별시 서대문구 연세로 50 ', '신촌동'],
 ['서울특별시 은평구 불광천길 436 ', '응암동'],
 ['서울특별시 서대문구 홍제동 통일로 397'],
 ['서울특별시 은평구 진관동 진관2로 57-7'],
 ['서울특별시 은평구 녹번동 153-1'],
 ['서울특별시 서대문구 독립문로14길 33'],
 ['서울특별시 은평구 통일로 1034 ', '진관동'],
 ['서울특별시 서대문구 남가좌동 377'],
 ['서울특별시 서대문구 연희로32길 48 ', '연희동'],
 ['서울특별시 은평구 통일로 659'],
 ['서울특별시 서대문구 통일로26길 41 ', '홍제동'],

In [94]:
chargingDF['주소'].str.contains('[(]')

0         False
1         False
2         False
3         False
4         False
          ...
638697    False
638698    False
638699    False
638700    False
638701    False
Name: 주소, Length: 638702, dtype: object

In [81]:
chargingDF_2[chargingDF['주소'].str.contains('(')]

error: missing ), unterminated subpattern at position 0

In [ ]:
hjDF['month'] = train.date_time.dt.month                    # 월(숫자)
hjDF['day'] = train.date_time.dt.day                        # 일(숫자)
hjDF['hour'] = train.date_time.dt.hour                      # 시(숫자)
hjDF['weekday'] = train.date_time.dt.weekday                # 요일(숫자)
hjDF['dayofyear'] = train.date_time.dt.dayofyear            # 연 기준 몇일째(숫자)